### ISSUE TITLE
Summary Plot Errors on Dashboard 

### ISSUE THREAD

**Issue by akshaym2497** [explainX/explainx#3]
Everything on the dashboard shows up except for the summary plots where there are 2 callback errors and both are related to AttributeError: 'DataFrame' object has no attribute 'convert_dtypes'. 

![image](https://user-images.githubusercontent.com/63619923/85329722-0c75c300-b4a1-11ea-8c01-cb9a12b5186d.png)

**Comment by akshaym2497** [comment]
This error got fixed when I updated my pandas from 0.25.1 to 1.0.5.

**Comment by ms8909** [comment]
Thanks for the feedback.

You would have to use the new version of Pandas Library that has the attribute **convert_dtypes'** . To update Pandas, please use the following.

**_pip install pandas==1.0.5_**
